=== Sushrut1101/android_vendor_qcom_proprietary/common/scripts/SecImage/config/xsd/secimage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.qualcomm.com/secimage"
    xmlns:tns="http://www.qualcomm.com/secimage">

    <element name="secimage">
        <complexType>
            <all>
                <element name="metadata" type="tns:complex_metadata" />
                <element name="general_properties" type="tns:complex_general_properties" />
                <element name="parsegen" type="tns:complex_parsegen" maxOccurs="1" minOccurs="0"/>
                <element name="signing" type="tns:complex_signing" />
                <element name="post_process" type="tns:complex_post_process" />
                <element name="images_list" type="tns:complex_images_list" />
                <element name="data_provisioning" type="tns:complex_data_provisioning" />
            </all>
        </complexType>
    </element>

    <complexType name="complex_metadata">
        <all>
            <element name="chipset" type="string" />
            <element name="version" type="string" />
        </all>
    </complexType>

    <complexType name="complex_general_properties">
        <all>
            <element name="selected_signer" type="string" />
            <element name="selected_encryptor" type="string" />
            <element name="selected_cert_config" type="string" />
            <element name="max_cert_size" type="int" />
            <element name="key_size" type="int" maxOccurs="1" minOccurs="0"/>
            <element name="num_certs_in_certchain" type="int" />
            <element name="num_root_certs" type="int" />
            <element name="testsig_serialnum" type="string" maxOccurs="1" minOccurs="0" />
            <element name="mrc_index" type="int" maxOccurs="1" minOccurs="0" />
            <element name="msm_part" type="string" maxOccurs="1" minOccurs="0" />
            <element name="oem_id" type="string" />
            <element name="model_id" type="string" />
            <element name="sw_id" type="string" maxOccurs="1" minOccurs="0" />
            <element name="app_id" type="string" maxOccurs="1" minOccurs="0" />
            <element name="crash_dump" type="string" maxOccurs="1" minOccurs="0" />
            <element name="rot_en" type="string" maxOccurs="1" minOccurs="0" />
            <element name="soc_hw_version" type="string" maxOccurs="1" minOccurs="0" />
            <element name="soc_vers" type="string" maxOccurs="1" minOccurs="0" />
            <element name="mask_soc_hw_version" type="string" maxOccurs="1" minOccurs="0" />
            <element name="in_use_soc_hw_version" type="int" maxOccurs="1" minOccurs="0" />
            <element name="use_serial_number_in_signing" type="int" maxOccurs="1" minOccurs="0" />
            <element name="serial_number" type="string" maxOccurs="1" minOccurs="0" />
            <element name="debug" type="string" maxOccurs="1" minOccurs="0" />
            <element name="debug_serials" type="tns:complex_debug_serials" maxOccurs="1" minOccurs="0"/>
            <element name="exponent" type="int" maxOccurs="1" minOccurs="0" />
            <element name="object_id" type="tns:complex_oid" maxOccurs="1" minOccurs="0" />
            <element name="pmbl_properties" type="tns:complex_pmbl_properties" maxOccurs="1" minOccurs="0" />
            <element name="cass_capability" type="string" maxOccurs="1" minOccurs="0" />
            <element name="hash_pageseg_as_segment" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="hash_algorithm" type="string" maxOccurs="1" minOccurs="0" />
            <element name="segment_hash_algorithm" type="string" maxOccurs="1" minOccurs="0" />
            <element name="cass_attest_cert" type="string" maxOccurs="1" minOccurs="0" />
            <element name="rsa_padding" type="string" maxOccurs="1" minOccurs="0" />
            <element name="hmac" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="secboot_version" type="string" maxOccurs="1" minOccurs="0" />
            <element name="qc_sign" type="boolean" maxOccurs="1" minOccurs="0" default="false"/>
            <element name="oem_sign" type="boolean" maxOccurs="1" minOccurs="0" default="true"/>
            <element name="UIE_key" type="string" maxOccurs="1" minOccurs="0" />
            <element name="UIE_capability" type="string" maxOccurs="1" minOccurs="0" />
            <element name="UIE_root_key_type" type="int" maxOccurs="1" minOccurs="0" />
            <element name="oem_id_independent" type="int" maxOccurs="1" minOccurs="0" />
            <element name="revocation_enablement" type="string" maxOccurs="1" minOccurs="0" />
            <element name="activation_enablement" type="string" maxOccurs="1" minOccurs="0" />
            <element name="dsa_type" type="string" maxOccurs="1" minOccurs="0" />
            <element name="ecdsa_curve" type="string" maxOccurs="1" minOccurs="0" />
        </all>
    </complexType>
    
    <complexType name="complex_debug_serials">
        <sequence>
            <element name="serial" type="string" maxOccurs="200" minOccurs="0" />
        </sequence>
    </complexType>

    <complexType name="complex_parsegen">
        <all>
            <element name="image_types_list" type="tns:complex_image_types_list" maxOccurs="1" minOccurs="0"/>
        </all>
    </complexType>

    <complexType name="complex_image_types_list">
        <sequence>
            <element name="image_type" type="tns:complex_image_type" maxOccurs="unbounded" minOccurs="1" />
        </sequence>
    </complexType>

    <complexType name="complex_image_type">
        <all>
            <element name="file_type" type="string"/>
            <element name="mbn_properties" type="tns:complex_mbn_properties" maxOccurs="1" minOccurs="0" />
            <element name="elf_properties" type="tns:complex_elf_properties" maxOccurs="1" minOccurs="0" />
            <element name="ewm_properties" type="tns:complex_ewm_properties" maxOccurs="1" minOccurs="0" />
            <element name="pmbl_properties" type="tns:complex_pmbl_properties" maxOccurs="1" minOccurs="0" />
        </all>
        <attribute name="id" type="string" use="required" />
    </complexType>

    <complexType name="complex_mbn_properties">
        <all>
            <element name="header_size" type="int" />
        </all>
    </complexType>

    <complexType name="complex_pmbl_properties">
        <all>
            <element name="preamble_size" type="int" maxOccurs="1" minOccurs="0" />
            <element name="has_magic_num" type="boolean" />
            <element name="ota_enabled" type="boolean" />
            <element name="page_size" type="int" maxOccurs="1" minOccurs="0" />
            <element name="num_of_pages" type="int" maxOccurs="1" minOccurs="0" />
            <element name="min_size_with_pad" type="int" maxOccurs="1" minOccurs="0" />
        </all>
    </complexType>

    <complexType name="complex_elf_properties">
        <all>
            <element name="has_hash_table" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="max_elf_segments" type="int" maxOccurs="1" minOccurs="0"/>
            <element name="image_type" type="int" />
            <element name="hash_seg_placement" type="string" maxOccurs="1" minOccurs="0" />
            <element name="validate_ph_addrs" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="validate_vir_addrs" type="boolean" maxOccurs="1" minOccurs="0" />
        </all>
    </complexType>

    <complexType name="complex_ewm_properties">
        <all>
            <element name="image_entry" type="string" />
            <element name="relocatable" type="boolean" />
        </all>
    </complexType>

    <complexType name="complex_signing">
        <all>
            <element name="signer_attributes" type="tns:complex_signer_attributes" />
        </all>
    </complexType>

    <complexType name="complex_oid">
        <attribute name="name" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="tcg"></enumeration>
                    <enumeration value="feature_id"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="min" type="string" />
        <attribute name="max" type="string" />
    </complexType>

    <complexType name="complex_signer_attributes">
        <all>
            <element name="cass_signer_attributes" type="tns:complex_cass_signer_attributes"
                maxOccurs="1" minOccurs="0" />
            <element name="remote_client_signer_attributes" type="tns:complex_remote_client_signer_attributes"
                maxOccurs="1" minOccurs="0" />
            <element name="remote_signer_attributes" type="tns:complex_remote_signer_attributes"
                maxOccurs="1" minOccurs="0" />
        </all>
    </complexType>

    <complexType name="complex_cass_signer_attributes">
        <all>
            <element name="server" type="tns:complex_server" maxOccurs="1" minOccurs="0" />
            <element name="user_identity" type="tns:complex_user_identity" />
        </all>
    </complexType>

    <complexType name="complex_remote_client_signer_attributes">
        <all>
            <element name="send_signing_overrides" type="boolean"/>
        </all>
    </complexType>

    <complexType name="complex_remote_signer_attributes">
        <all>
            <element name="allow_signing_overrides" type="boolean"/>
        </all>
    </complexType>

    <complexType name="complex_server">
        <all>
            <element name="host" type="string" />
            <element name="port" type="int" />
            <element name="trust_keystore" type="string" />
            <element name="trust_keystore_password" type="string" maxOccurs="1" minOccurs="0" />
            <element name="trust_keystore_type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="JKS" />
                        <enumeration value="PKCS12" />
                    </restriction>
                </simpleType>
            </element>
            <element name="host_validation_mode" maxOccurs="1" minOccurs="0">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="TEST" />
                        <enumeration value="STAGE_PROD" />
                    </restriction>
                </simpleType>
            </element>
        </all>
    </complexType>

    <complexType name="complex_user_identity">
        <all>
            <element name="token_identity_slot" type="int" maxOccurs="1" minOccurs="0" />
            <element name="token_password" type="string" maxOccurs="1" minOccurs="0" />
            <element name="keystore_file" type="string" maxOccurs="1" minOccurs="0" />
            <element name="token_driver_home" type="tns:complex_token_driver_home" />
            <element name="keystore_type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="PKCS11" />
                        <enumeration value="PKCS12" />
                    </restriction>
                </simpleType>
            </element>
        </all>
    </complexType>

    <complexType name="complex_token_driver_home">
        <all>
            <element name="windows" type="string" />
            <element name="linux" type="string" />
        </all>
    </complexType>

    <complexType name="complex_post_process">
        <all>
            <element name="pil_splitter" type="string" />
        </all>
    </complexType>

    <complexType name="complex_data_provisioning">
        <all>
            <element name="base_path" type="string" />
        </all>
    </complexType>

    <complexType name="complex_images_list">
        <sequence>
            <element name="image" type="tns:complex_image" maxOccurs="unbounded"
                minOccurs="1" />
        </sequence>
    </complexType>

    <complexType name="complex_image">
        <all>
            <element name="pil_split" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="general_properties_overrides" type="tns:complex_general_properties_overrides" />
            <element name="meta_build_location" type="string" maxOccurs="1" minOccurs="0" />
            <element name="post_process_commands" type="string" maxOccurs="1" minOccurs="0" />
        </all>
        <attribute name="sign_id" type="string" use="required" />
        <attribute name="name" type="string" use="optional" />
        <attribute name="image_type" type="string" use="required" />
        <attribute name="cert_config" type="string" use="optional" />
        <attribute name="output_file_name" type="string" use="optional" />
    </complexType>

    <complexType name="complex_general_properties_overrides">
        <all>
            <element name="max_cert_size" type="int" maxOccurs="1" minOccurs="0" />
            <element name="key_size" type="int" maxOccurs="1" minOccurs="0" />
            <element name="num_certs_in_certchain" type="int" maxOccurs="1" minOccurs="0" />
            <element name="num_root_certs" type="int" maxOccurs="1" minOccurs="0" />
            <element name="testsig_serialnum" type="string" maxOccurs="1" minOccurs="0" />
            <element name="mrc_index" type="int" maxOccurs="1" minOccurs="0" />
            <element name="msm_part" type="string" maxOccurs="1" minOccurs="0" />
            <element name="oem_id" type="string" maxOccurs="1" minOccurs="0" />
            <element name="model_id" type="string" maxOccurs="1" minOccurs="0" />
            <element name="sw_id" type="string" maxOccurs="1" minOccurs="0" />
            <element name="app_id" type="string" maxOccurs="1" minOccurs="0" />
            <element name="crash_dump" type="string" maxOccurs="1" minOccurs="0" />
            <element name="rot_en" type="string" maxOccurs="1" minOccurs="0" />
            <element name="soc_hw_version" type="string" maxOccurs="1" minOccurs="0" />
            <element name="soc_vers" type="string" maxOccurs="1" minOccurs="0" />
            <element name="mask_soc_hw_version" type="string" maxOccurs="1" minOccurs="0" />
            <element name="in_use_soc_hw_version" type="int" maxOccurs="1" minOccurs="0" />
            <element name="use_serial_number_in_signing" type="int" maxOccurs="1" minOccurs="0" />
            <element name="serial_number" type="string" maxOccurs="1" minOccurs="0" />
            <element name="debug" type="string" maxOccurs="1" minOccurs="0" />
            <element name="debug_serials" type="tns:complex_debug_serials" maxOccurs="1" minOccurs="0"/>
            <element name="exponent" type="int" maxOccurs="1" minOccurs="0" />
            <element name="object_id" type="tns:complex_oid" maxOccurs="1" minOccurs="0" />
            <element name="cass_capability" type="string" maxOccurs="1" minOccurs="0" />
            <element name="hash_pageseg_as_segment" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="hash_algorithm" type="string" maxOccurs="1" minOccurs="0" />
            <element name="segment_hash_algorithm" type="string" maxOccurs="1" minOccurs="0" />
            <element name="cass_attest_cert" type="string" maxOccurs="1" minOccurs="0" />
            <element name="rsa_padding" type="string" maxOccurs="1" minOccurs="0" />
            <element name="hmac" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="secboot_version" type="string" maxOccurs="1" minOccurs="0" />
            <element name="qc_sign" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="oem_sign" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="UIE_key" type="string" maxOccurs="1" minOccurs="0" />	    
            <element name="UIE_capability" type="string" maxOccurs="1" minOccurs="0" />
            <element name="UIE_root_key_type" type="int" maxOccurs="1" minOccurs="0" />
            <element name="oem_id_independent" type="int" maxOccurs="1" minOccurs="0" />
            <element name="revocation_enablement" type="string" maxOccurs="1" minOccurs="0" />
            <element name="activation_enablement" type="string" maxOccurs="1" minOccurs="0" />
            <element name="dsa_type" type="string" maxOccurs="1" minOccurs="0" />
            <element name="ecdsa_curve" type="string" maxOccurs="1" minOccurs="0" />
        </all>
    </complexType>

</schema>

=== Sushrut1101/android_vendor_qcom_proprietary/common/scripts/SecImage/config/integration/secimage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================

  Copyright (c) 2013-2016 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.

===============================================================================
-->

<tns:secimage xmlns:tns="http://www.qualcomm.com/secimage"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.qualcomm.com/secimage ../xsd/secimage.xsd">

    <metadata>
        <chipset>default</chipset>
        <version>2.0</version>
    </metadata>

    <!--
       See documentation on general_properties below.
    -->
    <general_properties>
        <selected_signer>local</selected_signer>
        <selected_encryptor>unified_encryption_2_0</selected_encryptor>
        <selected_cert_config>qc_presigned_certs</selected_cert_config>

        <key_size>2048</key_size>
        <exponent>65537</exponent>

        <mrc_index>0</mrc_index>
        <num_root_certs>1</num_root_certs>

        <msm_part>0x00000000</msm_part>
        <oem_id>0x0000</oem_id>
        <model_id>0x0000</model_id>
        <debug>0x0000000000000002</debug>

        <max_cert_size>2048</max_cert_size>
        <num_certs_in_certchain>3</num_certs_in_certchain>
    </general_properties>

    <!--
        ***general_properties***

        The default properties for all images. These properties maybe overridden
        per image in the 'images' section below as needed.

        Supported signer are:
        local: use local signer with test keys

        Supported encryptor are:
        ssd_encryption: legacy encryption for OTA, supports MBN and ELF images.
        unified_encryption_2_0: supports ELF images. Image must be signed to encrypt

        msm_part: jtag_id for signing. (in hex)
        oem_id: oem_id for signing. (in hex)
        model_id: model_id for signing. (in hex)
        debug: debug_id for signing. (in hex)
        exponent: exponent value used in attestation key generation.

        max_cert_size: Maximum size (in bytes) of one certificate.
        key_size: Size (in bits) of the key used for signing.
        num_certs_in_certchain: Number of certificates in the certificate chain.
        num_root_certs: Number of root certificates in the certificate chain.
    -->

    <parsegen>
        <image_types_list>
            <image_type id='elf_wrapped_mbn'>
                <!-- Type of file format -->
                <file_type>ewm</file_type>

                <ewm_properties>
                    <image_entry>0x01200000</image_entry>
                    <relocatable>false</relocatable>
                </ewm_properties>

                <elf_properties>
                    <has_hash_table>false</has_hash_table>
                    <image_type>0</image_type>
                </elf_properties>

                <mbn_properties>
                    <header_size>80</header_size>
                </mbn_properties>

            </image_type>
        </image_types_list>
    </parsegen>

    <!-- Signing configurations used by secimage. -->
    <signing>
        <signer_attributes>
        </signer_attributes>
    </signing>

    <post_process>
        <pil_splitter>$(META_BUILD)/common/tools/misc/pil-splitter.py</pil_splitter>
    </post_process>

    <data_provisioning>
        <base_path>./../../resources/data_prov_assets/</base_path>
    </data_provisioning>

    <images_list>
        <image sign_id="sbl1" name="sbl1.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000000</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="sbl1_mbn" name="sbl1.mbn" image_type="mbn_80b">
            <general_properties_overrides>
                <sw_id>0x0000000000000000</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="sbl1_nand" name="sbl1.mbn" image_type="elf_preamble">
            <general_properties_overrides>
                <sw_id>0x0000000000000000</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="sbl1_hash_64b_align" name="sbl1.mbn" image_type="elf_end_64b_aligned">
            <general_properties_overrides>
                <sw_id>0x0000000000000000</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="mba" name="mba.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000001</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="mba_mbn" name="mba.mbn" image_type="mbn_80b">
            <general_properties_overrides>
                <sw_id>0x0000000000000001</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="mba_ewm" name="mba.mbn" image_type="elf_wrapped_mbn">
            <general_properties_overrides>
                <sw_id>0x0000000000000001</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="qdsp6sw" name="qdsp6sw.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000002</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="emmcbld" name="MPRG*.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000003</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="emmcbld_mbn" name="MPRG*.mbn" image_type="mbn_80b">
            <general_properties_overrides>
                <sw_id>0x0000000000000003</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="ENPRG_mbn" name="ENPRG*.mbn" image_type="mbn_80b">
            <general_properties_overrides>
                <sw_id>0x0000000000000003</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="ENPRG" name="ENPRG*.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000003</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="NPRG_mbn" name="NPRG*.mbn" image_type="mbn_40b">
            <general_properties_overrides>
                <sw_id>0x0000000000000003</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="NPRG" name="NPRG*.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000003</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="adsp" name="dsp*.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000004</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="devcfg" name="devcfg.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000005</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="acpi" name="acpi.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000005</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="tz" name="tz.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000007</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="appsboot" name="appsboot.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000009</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="appsbl" name="emmc_appsboot.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000009</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="uefi" name="uefi_sign_ready.mbn" image_type="elf_as_bin">
            <general_properties_overrides>
                <sw_id>0x0000000000000009</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="rpm" name="rpm.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x000000000000000A</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="imc" name="imc.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x000000000000000A</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="wcnss" name="wcnss.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x000000000000000D</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="vss" name="venus.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x000000000000000E</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="apps" name="apps.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x000000000000000E</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="avs" name="avs.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000011</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="sdi" name="sdi.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000012</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="sdi_mbn" name="sdi.mbn" image_type="mbn_40b">
